name: Build U-Boot Image

on:
  push:
    branches:
      - sc-rk3399-mainline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Checkout rkbin repo
      uses: actions/checkout@v3
      with:
        repository: rockchip-linux/rkbin
        ref: d6ccfe401ca84a98ca3b85c12b9554a1a43a166c
        path: rkbin
    
    - name: Build idbloader.img
      run: |
        rkbin/tools/mkimage -n rk3399 -T rksd -d rkbin/bin/rk33/rk3399_ddr_800MHz_v1.30.bin idbloader.img
        cat rkbin/bin/rk33/rk3399_miniloader_v1.26.bin >> idbloader.img
        
    - name: Build trust.img
      run: |
        cd rkbin
        tools/trust_merger --pack ../RK3399TRUST.ini
        mv trust.img ../trust.img

    - name: Install aarch64 toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Apply defconfig
      run: make CROSS_COMPILE=aarch64-linux-gnu- smartcross_defconfig

    - name: Build U-Boot image
      run: make CROSS_COMPILE=aarch64-linux-gnu- -j
      
    - name: Pack U-Boot Image
      run: rkbin/tools/loaderimage --pack --uboot u-boot-dtb.bin uboot.img 0x00200000

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: smartcross-boot
        path: |
          uboot.img
          idbloader.img
          trust.img

